FROM node:20-alpine as build
WORKDIR /app
COPY package.json .
RUN npm install -g pnpm
RUN pnpm i
COPY . .
RUN pnpm build

FROM node:20-alpine
WORKDIR /usr/app
COPY --from=build /app/dist/frontend/ ./
CMD node server/server.mjs
EXPOSE 4000
