FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM build
RUN dotnet tool install -g dotnet-ef
ENTRYPOINT dotnet ef database update -p /app/src/Infrastructure -s /app/src/Web

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "backend.Web.dll"]